### ISSUE TITLE
Does the local_lm works with cpu only?

### ISSUE THREAD

**Issue by pacozaa** [deep-diver/llamaduo#27]
Hi interesting project! I would like to know if this works with cpu only machine like mac.

**Comment by juyongjiang** [comment]
> Hi interesting project! I would like to know if this works with cpu only machine like mac.

Hi, thank you for your interest. Generally, Local LM refers to models with considerably fewer parameters and available model checkpoints, such as the LM with GPT-2 Medium 355M, Gemma 2B, or 7B. These models can be run on your available GPUs as well as on CPUs. : )

**Comment by juyongjiang** [comment]
> Hi interesting project! I would like to know if this works with cpu only machine like mac.

@pacozaa Hi, thank you for your interest. I believe it can operate on CPU-only machines, but it will not be as fast as on GPU devices. Please refer to the guideline at [https://rentry.org/cpu-lora](https://rentry.org/cpu-lora) and use [https://github.com/ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp). : )
