### ISSUE TITLE
Cloud Integration (fine-tuning, evaluation)

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/llamaduo#7]
the target cloud environments could be:
- Google Cloud Platform
- [dstack Sky](https://sky.dstack.ai/)
- [jarvislabs.ai](https://jarvislabs.ai/)

for evaluation, the current implementation should be further splitted into:
- local LLM's batch inferencing (GPU server on Cloud)
    - store the batch inference results somewhere (maybe temporarily)
- evaluation on the batch inference via service LLM (either of VM on GitHub Action or Cheap CPU Cloud)

**Comment by sayakpaul** [comment]
What does integration mean here?
